services:
  - type: worker
    name: telegram-group-bot
    env: python
    plan: free
    buildCommand: "pip install -r requirements.txt"
    startCommand: "python main.py"
    disks:
      - name: sessions-data
        mountPath: /app/sessions
        sizeGB: 1
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.4
      - key: API_ID
        sync: false
      - key: API_HASH
        sync: false
      - key: BOT_TOKEN
        sync: false
      - key: ENCRYPTION_KEY
        sync: false
      - key: ADMIN_USER_ID
        sync: false
      - key: MASTER_PASSWORD_HASH
        sync: false
      - key: GEMINI_API_KEY
        sync: false
